app:
  dns: ourlib.ddns.net
  deployment:
    replicaCount: 1

    image: 
      rep: 644435390668.dkr.ecr.eu-west-1.amazonaws.com/our_library
      tag: 1.0.11
      pullPolicy: Always 

# Values for MongoDB child/dependency chart
mongodb:
  fullnameOverride: mongodb
  architecture: "replicaset"
  replicaCount: 2 
  auth:
    enabled: true
    usernames: ["myuser"]
    # passwords: ["mypass"]
    databases: ["mydb"]
    existingSecret: "external-db-secrets" 
    rootUser: "root"
  persistence:
    enabled: true
    storageClass: "ebs-csi-gp3" 
    size: 1Gi
  arbiter:
    enabled: true
