apiVersion: apps/v1
kind: Deployment
metadata:
  name: ourlib-deployment
spec:
  replicas: {{ .Values.app.deployment.replicaCount }}  #Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: ourlib
  template:
    metadata:
      labels:
        app: ourlib
    spec:
      containers:
      - name: ourlib-container
        image: "{{ .Values.app.deployment.image.rep }}:{{ .Values.app.deployment.image.tag }}" 
        imagePullPolicy: {{.Values.app.deployment.image.pullPolicy}}
        ports:
        - name: web # For prometheus 
          containerPort: 7070 # could also call from the port in the env section 
        resources:
          requests:
            memory: "64Mi"  # Request 64 megabytes of memory
            cpu: "250m"      # Request 250 milliCPU (0.25 CPU core)
          limits:
            memory: "128Mi"  # Limit memory usage to 128 megabytes
            cpu: "500m"      # Limit CPU usage to 500 milliCPU (0.5 CPU core)     
        #Replace data in the .env folder of both backend and frontend 
        #username
        #password
        #database
        #mongodb-passwords
        #mongodb-root-password
        #mongodb-replica-set-key

        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: external-db-secrets
              key: MONGO_URL
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: external-db-secrets
              key: DATABASE_NAME
        - name: DNS_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: ourlib-config
              key: DNS_ADDRESS
        - name: VERSION
          value: "{{ .Values.app.deployment.image.tag }}"