apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "git@github.com:adigaandyt/ourlibrary_gitops.git"
    path: "infra-apps"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  # sshPrivateKeySecret:
  #   name: private-repo-secret  # Name of the secret containing the SSH private key
  #   key: sshPrivateKey
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true # or false, depending on your needs
      selfHeal: true # or false, based on preference