elasticsearch:
  # Elasticsearch values
  global:
    elasticsearch:
      service:
        name: elasticsearch
        ports:
          restAPI: 9200
    kibanaEnabled: true

  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

  sysctlImage:
    ## Enable kernel settings modifier image - not available in GKE Autopilot
    ## See https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
    enabled: true

  kibana:
    ingress:
      enabled: true
      hostname: letsreview-kibana.ddns.net
      path: /
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      tls: true
      ingressClassName: "nginx"
    persistence:
      enabled: true
      size: 5Gi
    service:
      port:
        http: 5601

# fluentd:
#   aggregator:
#     enabled: false
#   forwarder:
#     enabled: true
#     configFile: fluentd.conf
#     configMap: "fluentd-configmap"


fluent-bit:
  logLevel: info
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 5
          Log_Level debug
          Parsers_File /fluent-bit/etc/parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 8080
          Health_Check On
          Trace_Error On

    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*nginx-controller-ingress*.log
          multiline.parser docker, cri
          Tag ingress.*
          Mem_Buf_Limit 100MB
          Skip_Long_Lines On

    filters: |
      [FILTER]
          Name kubernetes
          Match ingress.*
          Merge_Log On
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

    outputs: |
      [OUTPUT]
          Name es
          Match ingress.*
          Host elasticsearch-master
          Port 9200
          HTTP_User elastic
          HTTP_Passwd 9fVpTSmmeC3IzEiE
          tls On
          tls.verify Off
          Logstash_Format On
          Logstash_Prefix ingress-logs
          Retry_Limit False
          Suppress_Type_Name On
