apiVersion: apps/v1
kind: Deployment
metadata:
  name: ourlib-deployment
spec:
  replicas: 1  #Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: ourlib
  template:
    metadata:
      labels:
        app: ourlib
    spec:
      initContainers:
      - name: init-mongodb
        image: 644435390668.dkr.ecr.eu-west-1.amazonaws.com/our_library:main-24
        command:
            - "sh"
            - "-c"
            - "sleep 30"
        # Add environment variables or configuration as needed for the initContainer
      containers:
      - name: ourlib-container
        image: 644435390668.dkr.ecr.eu-west-1.amazonaws.com/our_library:main-24  # Replace with your ECR URL and image tag
        ports:
        - containerPort: 8000  # Your application listens on port 8000
        resources:
          requests:
            memory: "64Mi"  # Request 64 megabytes of memory
            cpu: "250m"      # Request 250 milliCPU (0.25 CPU core)
          limits:
            memory: "128Mi"  # Limit memory usage to 128 megabytes
            cpu: "500m"      # Limit CPU usage to 500 milliCPU (0.5 CPU core)     
        # Replace data in the .env folder of both backend and frontend
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: ourlib-secret
              key: JWT_KEY
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: ourlib-secret
              key: MONGO_URL
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ourlib-config
              key: PORT
    #   dependsOn:
    #   - name: mongodb-service-name  # Replace with the actual name of your MongoDB service
    #       condition: Ready