apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ourlib-ingress
spec:
  ingressClassName: nginx 
  rules:
    - host: ourlib.ddns.net
      http:
        paths:
          - backend:
              service: 
                name: ourlib-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            
