apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ourlib-ingress
spec:
  ingressClassName: nginx 
  rules:
    - host: ourlib.ddns.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: ourlib-service
                namespace: ourlib
                port:
                  number: 80
resource:
  customizations: |
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs