apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ourlib-app
  namespace: kps
spec:
  selector:
    matchLabels:
      app: ourlib
      namespace: ourlib
  endpoints:
- interval: 30s
    targetPort: 9090
    path: /metrics
