apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ourlib
  namespace: kps
  labels:
    prometheus: main
spec:
  namespaceSelector:
    matchesNames:
      - ourlib
  selector:
    matchLabels:
      app: ourlib
  endpoints:
    - port: web
      path: /metrics
