apiVersion: v1
kind: Service
metadata:
  name: ourlib-service
  namespace: ourlib
  labels:
    app: ourlib
spec:
  selector:
    app: ourlib
  ports:
    - protocol: TCP
      name: web
      port: 80
      targetPort: 7070