apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.app.name }}-deployment
spec:
  replicas: {{ .Values.app.deployment.replicaCount }}  #Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}-container
        image: "{{ .Values.app.deployment.image.rep }}:{{ .Values.app.deployment.image.tag }}" 
        imagePullPolicy: {{.Values.app.deployment.image.pullPolicy}}
        ports:
        - name: web 
          containerPort: 7070 
        resources:
          requests:
            memory: "64Mi"  
            cpu: "250m"      
          limits:
            memory: "128Mi"  
            cpu: "500m"        
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-config
              key: MONGO_URL
        - name: db_name
          valueFrom:
            secretKeyRef:
              name: external-db-secrets
              key: db_name
        - name: DNS_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-config
              key: DNS_ADDRESS
        - name: VERSION
          value: "{{ .Values.app.deployment.image.tag }}"