apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
data:
  DNS_ADDRESS: "https://{{ .Values.app.dns }}"
  MONGO_URL: mongodb://myuser:mypass@mongodb-headless:27017/mydb?replicaSet=rs0

