apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Values.app.name }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"  # Reference your ClusterIssuer
spec:
  ingressClassName: nginx
  rules:
  - host: {{.Values.app.dns}}
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.app.name }}-service
            port:
              number: 80
  tls:  # TLS configuration starts here
  - hosts:
    - {{.Values.app.dns}}
    secretName: {{ .Values.app.name }}-tls  # cert-manager will store the obtained certificate here
