apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}-monitor
  namespace: prometheus
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.app.name }} # service's selector app
  selector:
    matchLabels:
      app: {{ .Values.app.name }} # service should have this label
  endpoints:
  - port: web
    path: /metrics