apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:adigaandyt/LetsReview-GitOps.git  
      targetRevision: main
      path: charts/cert-manager
      helm:
        values: |
          installCRDs: true 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true