apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: 1.13.3
      chart: cert-manager
      helm:
        values: |
          installCRDs: true 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
