apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-app
  namespace: argocd  # Namespace where the Argo CD Application will be created
spec:
  project: default  # Project name (You can create a project before this step)
  source:
    repoURL: git@github.com:adigaandyt/LetsReview-GitOps.git  # URL of your Helm chart repository
    targetRevision: main  # The branch, tag, or commit you want to use
    path: charts/EFK  # Path to your Helm chart within the repository
  destination:
    server: 'https://kubernetes.default.svc'  # URL of your Kubernetes cluster
    namespace: efk  # Namespace where the Helm chart should be deployed
  syncPolicy:
    syncOptions:
      - CreateNamespace=true # automatically creates our custom namespace
    automated:
      prune: true # or false, depending on your needs
      selfHeal: true # or false, based on preference