apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-controller-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ggit@github.com:adigaandyt/ourlibrary_gitops.git
    targetRevision: main
    path: charts/external-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
