apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:adigaandyt/ourlibrary_gitops.git
      targetRevision: main
      path: kp-chart/kube-prometheus-stack-56.6.2.tgz
      helm:
        valueFiles:
          - kp-chart/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: kps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true