apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:adigaandyt/ourlibrary_gitops.git
      targetRevision: main
      path: kube-prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: kps
  syncPolicy:
    syncOptions:kube-prometheus-stack
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true