apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-application
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 55.8.1
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - "$mycharts/values/kps-values.yaml"
    - repoURL: git@github.com:adigaandyt/LetsReview-GitOps.git
      targetRevision: HEAD
      ref: mycharts
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true