apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx # Replace with the Helm chart repository URL
    targetRevision: 4.9.0 # Replace with the version of the Helm chart
    chart: ingress-nginx # Replace with the path to the Helm chart within the repository
  destination:
    server: "https://kubernetes.default.svc" # Replace with the Kubernetes cluster URL
    namespace: ingress # The namespace where you want to install the Ingress Controller
    createNamespace: true
  syncPolicy:
    # syncOptions:
    #   - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true