apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsreview-app
  namespace: argocd  
spec:
  project: default 
  source:
    repoURL: git@github.com:adigaandyt/LetsReview-GitOps.git  
    targetRevision: main  
    path: charts/letsreview-chart  
  destination:
    server: 'https://kubernetes.default.svc'  
    namespace: letsreview  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true 
    automated:
      prune: true 
      selfHeal: true 