app:
  deployment:
    replicaCount: 1

    image: 
      rep: 644435390668.dkr.ecr.eu-west-1.amazonaws.com/our_library
      tag: 1.0.4
      pullPolicy: IfNotPresent 

  # Can pass these to a config file for example but here I'm just using a hardcoded secret
  # Matching the values here to the mongodb helm values wont actually do anything
  # You have to change the hardcoded secret  
  # since you don't pass values to secrets
  
  mongo:
    username: myuser
    password: mypass
    mongodbDatabase: mydb
    hosts:
      - mongodb-0.mongodb-headless
      - mongodb-1.mongodb-headless
      - mongodb-2.mongodb-headless

# Values for MongoDB child/dependency chart
mongodb:
  fullnameOverride: mongodb
  architecture: "replicaset"
  replicaCount: 3
  auth:
    enabled: true
    usernames: ["myuser"]
    passwords: ["mypass"]
    databases: ["mydb"]
    existingSecret: "ourlib-secret" # This secret has to include  mongodb-passwords/mongodb-root-password/mongodb-replica-set-key
    rootUser: "root"
    rootPassword: "rootpass"
  persistence:
    enabled: true
    storageClass: "ebs-csi-gp3" # Specify the StorageClass you created for EBS gp3 volumes
    size: 1Gi
  arbiter:
    enabled: true
